

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

import Footer from "./Components/footer";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/app/context/ThemeContext";

const publishableKey = "pk_test_Y29tbXVuYWwtbWFjYXF1ZS05My5jbGVyay5hY2NvdW50cy5kZXYk"; 
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Morant-Renatl-Car",
  description: "Generated by create next app",
  icons: {
    icon: "/Assets/car-favicon.png", // Corrected favicon path (inside public folder)
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={publishableKey}>
      <ThemeProvider>
        <html lang="en">
          <body className={`${inter.className} bg-white text-black dark:bg-black dark:text-white`}>
            {children}
            <Footer />
            <Script
              src="//code.tidio.co/fcnfrnwjgbe2bcwwu3xgnhs7vjlbrdj3.js"
              strategy="afterInteractive" 
            />
            {/* <Chatbot/> */}
          </body>
        </html>
      </ThemeProvider>
    </ClerkProvider>
  );
}
