import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "./Components/footer";
import { ClerkProvider  } from "@clerk/nextjs";

const publishableKey = "pk_test_Y29tbXVuYWwtbWFjYXF1ZS05My5jbGVyay5hY2NvdW50cy5kZXYk"; // Add your actual publishable key here

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={publishableKey}>
      <html lang="en">
        <body className={`${inter.className} bg-[#F6F7F9]`}>
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
